name: termtosvg
version: '0.3.0+git' # just for humans, typically '1.2+git' or '1.3.2'
summary: Record terminal sessions as SVG animations
description: |
  A Linux terminal recorder written in Python
  which renders your command line sessions 
  as standalone SVG animations.

grade: stable
confinement: strict

apps:
  termtosvg:
    command: termtosvg
    plugs:
      - home

parts:
  termtosvg:
    source: https://github.com/nbedos/termtosvg.git
    plugin: python
    python-version: python3
    build-packages:
      - python3-pip
